{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fail\"\"\"\n>       assert False\nE       assert False\n\ntest_allure_command.py:22: AssertionError"}, "description": "this test fail", "start": 1655443771447, "stop": 1655443771447, "uuid": "429503bd-e9b0-4e98-84d6-63baee9ff506", "historyId": "93447b93b0e3aedc5a6007dad0c46fb1", "testCaseId": "45ca17d263822c8490205f9b7d863d97", "fullName": "test_allure_command#test_failure", "labels": [{"name": "suite", "value": "test_allure_command"}, {"name": "host", "value": "KIKO-Wang"}, {"name": "thread", "value": "2148-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure_command"}]}